### ISSUE TITLE
Import of datasets

### ISSUE THREAD

**Issue by wangjiusi** [bnpy/bnpy#12]
Hi, thank you for your great work!
I have learned a lot from your thesis.
After installing bnpy, I tried to import the relevant dataset as in the example. But it throws an error. 

`~$ python -m bnpy.Run AsteriskK8 FiniteMixtureModel Gauss EM --K=3`

`Traceback (most recent call last):
  File "/home/wangjiusi/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/wangjiusi/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/wangjiusi/bnpy/bnpy/Run.py", line 611, in <module>
    run()
  File "/home/wangjiusi/bnpy/bnpy/Run.py", line 94, in run
    doSaveToDisk, doWriteStdOut)
  File "/home/wangjiusi/bnpy/bnpy/Run.py", line 144, in _run_task_internal
    DataArgs = getKwArgsForLoadData(ReqArgs, UnkArgs, KwArgs)
  File "/home/wangjiusi/bnpy/bnpy/Run.py", line 309, in getKwArgsForLoadData
    datamod = __import__(ReqArgs['dataName'], fromlist=[])
ImportError: No module named AsteriskK8
`

when I run:
`
~$ python -m bnpy.Run  DATASET_PATH/faithful/faithful.csv  FiniteMixtureModel Gauss VB --nLap 1 --K 3
`
It throws a similar error:

`Traceback (most recent call last):
  File "/home/wangjiusi/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/wangjiusi/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/wangjiusi/bnpy/bnpy/Run.py", line 611, in <module>
    run()
  File "/home/wangjiusi/bnpy/bnpy/Run.py", line 94, in run
    doSaveToDisk, doWriteStdOut)
  File "/home/wangjiusi/bnpy/bnpy/Run.py", line 144, in _run_task_internal
    DataArgs = getKwArgsForLoadData(ReqArgs, UnkArgs, KwArgs)
  File "/home/wangjiusi/bnpy/bnpy/Run.py", line 309, in getKwArgsForLoadData
    datamod = __import__(ReqArgs['dataName'], fromlist=[])
ImportError: Import by filename is not supported.
`

**Comment by michaelchughes** [comment]
Thanks for your interest! I'll try to help as best I can.

What version of Python? (Just show output of terminal cmd "python --version")

## For the "AsteriskK8" example

Where in the docs did you find this fragment: "python -m bnpy.Run AsteriskK8"?

If you have a recent install of bnpy, we no longer support this syntax (where the dataset is provided by a named python module assumed to be on the python path). Instead, you should always provide the full path to the dataset (which is easier to debug). 

For example, if you installed bnpy to "/home/wangjiusi/bnpy/", then you could do:

```
cd /home/wangjiusi/bnpy/bnpy/datasets/AsteriskK8
cat x_dataset.csv ## Verify your current directory contains the dataset in question
python -m bnpy.Run x_dataset.csv FiniteMixtureModel Gauss EM --K 8 --output_path /tmp/results/
```

## For the "Faithful" example

Are you sure you have DATASET_PATH as an environment variable set appropriate?

Again the following code should work:

```
cd /home/wangjiusi/bnpy/bnpy/datasets/faithful
cat faithful.csv ## Verify your current directory contains the dataset in question
python -m bnpy.Run faithful.csv FiniteMixtureModel Gauss EM --K 3 --output_path /tmp/results/
```

**Comment by wangjiusi** [comment]
@michaelchughes 
Sorry for late reply.

The version of Python is 2.7.
Thank you a lot! Now, it works. By the way, your sharing is really great!
