### ISSUE TITLE
Import error ImportError: No module named lib.sparseResp.LibSparseResp

### ISSUE THREAD

**Issue by cyriltw** [bnpy/bnpy#22]
Installation is completed but when I try to import bnpy I get this error. I'm on Python 2.7, any idea what is the issue for it and how to fix it?

`>>> import bnpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "bnpy/__init__.py", line 20, in <module>
    import allocmodel
  File "bnpy/allocmodel/__init__.py", line 7, in <module>
    from topics.FiniteTopicModel import FiniteTopicModel
  File "bnpy/allocmodel/topics/FiniteTopicModel.py", line 3, in <module>
    import LocalStepManyDocs
  File "bnpy/allocmodel/topics/LocalStepManyDocs.py", line 15, in <module>
    from bnpy.util.lib.sparseResp.LibSparseResp \
ImportError: No module named lib.sparseResp.LibSparseResp`

**Comment by ameya98** [comment]
I'm having a lot of issues on 2.7 as well. 

- Had to downgrade munkres to v1.0.12. The current version 1.1.2 causes a SyntaxError on execution.
- After this, when running the HMM example:
```bash
python -m bnpy.Run temp/test.csv HDPHMM DiagGauss memoVB --K 8
```
I get `AttributeError: 'XData' object has no attribute 'nDoc'`.

**Comment by michaelchughes** [comment]
Thanks for the bug report! I'm trying to get both 2.7 and 3+ versions into
shape soon. Hopefully in next week or so.

**Comment by cyriltw** [comment]
Another issue is, 
`PendingDeprecationWarning: the matrix subclass is not the recommended way to represent matrices or deal with linear algebra (see https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html). Please adjust your code to use regular ndarray.`
This just causes the entire thing to crash on my end.
