### ISSUE TITLE
TypeError: Cannot overwrite C type memoryview

### ISSUE THREAD

**Issue by lmizrahi12** [bnpy/bnpy#28]
Getting a `TypeError: Cannot overwrite C type memoryview` when importing bnpy.  Bnpy was installed without Eigen and from the python3_compatability branch.
```
import bnpy

Traceback (most recent call last):
  File "/mnt/data/home/liron/anaconda3/envs/pytorch/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/mnt/data/home/liron/anaconda3/envs/pytorch/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/mnt/data/home/liron/anaconda3/envs/pytorch/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/mnt/data/home/liron/bnpy/bnpy/__init__.py", line 32, in <module>
    from . import allocmodel
  File "/mnt/data/home/liron/bnpy/bnpy/allocmodel/__init__.py", line 3, in <module>
    from .mix.FiniteMixtureModel import FiniteMixtureModel
  File "/mnt/data/home/liron/bnpy/bnpy/allocmodel/mix/FiniteMixtureModel.py", line 12, in <module>
    from bnpy.util.SparseRespUtil import sparsifyLogResp
  File "/mnt/data/home/liron/bnpy/bnpy/util/SparseRespUtil.py", line 9, in <module>
    from .SparseRespUtilX import calcSpRData_cython
  File "bnpy/util/SparseRespUtilX.pyx", line 8, in init bnpy.util.SparseRespUtilX
TypeError: Cannot overwrite C type memoryview
```
Here are the versions of the required packages:
- python => 3.6
- bnpy => 0.1.5
- numpy => 1.17.3
- scipy => 1.3.1
- Cython => 0.29
- sckit-learn => 0.21.3
- joblib => 0.13.2
- memory_profiler => 0.56.0
- munkres => 1.1.2
- numexpr => 2.7.0
- psutil => 5.6.3

**Comment by TabeaW** [comment]
I am facing the same problem, have you found a solution for this?

**Comment by XiChen-97** [comment]
Have you installed Eigen and Boost (instructions in the advanced installation)?
https://bnpy.readthedocs.io/en/latest/installation.html#

It seems that the C++ libraries are needed. Thanks.

**Comment by tinnguyen96** [comment]
Even with Eigen and Boost, I'm not able to install bnpy. Could it be that only certain versions of Eigen and Boost are compatible? The versions I have are Eigen-3.2.10 and Boost 1.75.
