### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by AsmaZbt** [bnpy/bnpy#29]
hello ,
i'm encountering some installation problems , and i don't understand the message error , i would be very grateful if you can help me :

this is the message : 

Running setup.py clean for bnpy
Failed to build bnpy
Installing collected packages: bnpy
    Running setup.py install for bnpy ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Twins\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Twins\\AppData\\Local\\Temp\\pip-req-build-3h70bojb\\setup.py'"'"'; __file__='"'"'C:\\Users\\Twins\\AppData\\Local\\Temp\\pip-req-build-3h70bojb\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Twins\AppData\Local\Temp\pip-record-z2bf6t67\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\Twins\AppData\Local\Temp\pip-req-build-3h70bojb\
    Complete output (236 lines):
    Warning: Environment variable EIGENPATH not found.
    Will not compile the following C++ extensions
     - libsparsemix (for L-sparse mixtures)
     - libfwdbwd (for fast local steps for HMMs)
    Warning: Environment variable BOOSTMATHPATH not found.
    Will not compile the following C++ extensions
     - libsparsetopics (for L-sparse topic models)
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\bnpy
    copying bnpy\HModel.py -> build\lib.win-amd64-3.6\bnpy
    copying bnpy\Run.py -> build\lib.win-amd64-3.6\bnpy
    copying bnpy\__init__.py -> build\lib.win-amd64-3.6\bnpy
    creating build\lib.win-amd64-3.6\bnpy\allocmodel
    copying bnpy/allocmodel\AllocModel.py -> build\lib.win-amd64-3.6\bnpy/allocmodel
    copying bnpy/allocmodel\__init__.py -> build\lib.win-amd64-3.6\bnpy/allocmodel
    creating build\lib.win-amd64-3.6\bnpy\allocmodel\hmm
    copying bnpy/allocmodel\hmm\FiniteHMM.py -> build\lib.win-amd64-3.6\bnpy/allocmodel\hmm
    copying bnpy/allocmodel\hmm\HDPHMM.py -> build\lib.win-amd64-3.6\bnpy/allocmodel\hmm
    copying bnpy/allocmodel\hmm\HDPHMMUtil.py -> build\lib.win-amd64-3.6\bnpy/allocmodel\hmm
    copying bnpy/allocmodel\hmm\HMMUtil.py -> build\lib.win-amd64-3.6\bnpy/allocmodel\hmm
    copying bnpy/allocmodel\hmm\__init__.py -> build\lib.win-amd64-3.6\bnpy/allocmodel\hmm
    creating build\lib.win-amd64-3.6\bnpy\allocmodel\hmm\lib
    copying bnpy/allocmodel\hmm\lib\LibFwdBwd.py -> build\lib.win-amd64-3.6\bnpy/allocmodel\hmm\lib
    copying bnpy/allocmodel\hmm\lib\__init__.py -> build\lib.win-amd64-3.6\bnpy/allocmodel\hmm\lib
    creating build\lib.win-amd64-3.6\bnpy\allocmodel\mix
    copying bnpy/allocmodel\mix\DPMixtureModel.py -> build\lib.win-amd64-3.6\bnpy/allocmodel\mix
    copying bnpy/allocmodel\mix\DPMixtureRestrictedLocalStep.py -> build\lib.win-amd64-3.6\bnpy/allocmodel\mix
    copying bnpy/allocmodel\mix\FiniteMixtureModel.py -> build\lib.win-amd64-3.6\bnpy/allocmodel\mix
    copying bnpy/allocmodel\mix\__init__.py -> build\lib.win-amd64-3.6\bnpy/allocmodel\mix
    creating build\lib.win-amd64-3.6\bnpy\allocmodel\relational
    copying bnpy/allocmodel\relational\FiniteAssortativeMMSB.py -> build\lib.win-amd64-3.6\bnpy/allocmodel\relational
    copying bnpy/allocmodel\relational\FiniteMMSB.py -> build\lib.win-amd64-3.6\bnpy/allocmodel\relational
    copying bnpy/allocmodel\relational\FiniteSMSB.py -> build\lib.win-amd64-3.6\bnpy/allocmodel\relational
    copying bnpy/allocmodel\relational\HDPAssortativeMMSB.py -> build\lib.win-amd64-3.6\bnpy/allocmodel\relational
    copying bnpy/allocmodel\relational\HDPMMSB.py -> build\lib.win-amd64-3.6\bnpy/allocmodel\relational
    copying bnpy/allocmodel\relational\__init__.py -> build\lib.win-amd64-3.6\bnpy/allocmodel\relational
    creating build\lib.win-amd64-3.6\bnpy\allocmodel\topics
    copying bnpy/allocmodel\topics\BetterLocalStep.py -> build\lib.win-amd64-3.6\bnpy/allocmodel\topics
    copying bnpy/allocmodel\topics\FiniteTopicModel.py -> build\lib.win-amd64-3.6\bnpy/allocmodel\topics
    copying bnpy/allocmodel\topics\HDPTopicModel.py -> build\lib.win-amd64-3.6\bnpy/allocmodel\topics
    copying bnpy/allocmodel\topics\HDPTopicRestrictedLocalStep.py -> build\lib.win-amd64-3.6\bnpy/allocmodel\topics
    copying bnpy/allocmodel\topics\HDPTopicRestrictedLocalStep2.py -> build\lib.win-amd64-3.6\bnpy/allocmodel\topics
    copying bnpy/allocmodel\topics\HDPTopicUtil.py -> build\lib.win-amd64-3.6\bnpy/allocmodel\topics
    copying bnpy/allocmodel\topics\LocalStepLogger.py -> build\lib.win-amd64-3.6\bnpy/allocmodel\topics
    copying bnpy/allocmodel\topics\LocalStepManyDocs.py -> build\lib.win-amd64-3.6\bnpy/allocmodel\topics
    copying bnpy/allocmodel\topics\LocalStepSingleDoc.py -> build\lib.win-amd64-3.6\bnpy/allocmodel\topics
    copying bnpy/allocmodel\topics\LocalStepSingleDocSimpler.py -> build\lib.win-amd64-3.6\bnpy/allocmodel\topics
    copying bnpy/allocmodel\topics\OptimizerRhoOmega.py -> build\lib.win-amd64-3.6\bnpy/allocmodel\topics
    copying bnpy/allocmodel\topics\OptimizerRhoOmegaBetter.py -> build\lib.win-amd64-3.6\bnpy/allocmodel\topics
    copying bnpy/allocmodel\topics\__init__.py -> build\lib.win-amd64-3.6\bnpy/allocmodel\topics
    creating build\lib.win-amd64-3.6\bnpy\allocmodel\tree
    copying bnpy/allocmodel\tree\__init__.py -> build\lib.win-amd64-3.6\bnpy/allocmodel\tree
    creating build\lib.win-amd64-3.6\bnpy\birthmove
    copying bnpy/birthmove\BCleanup.py -> build\lib.win-amd64-3.6\bnpy/birthmove
    copying bnpy/birthmove\BCreateManyProposals.py -> build\lib.win-amd64-3.6\bnpy/birthmove
    copying bnpy/birthmove\BCreateOneProposal.py -> build\lib.win-amd64-3.6\bnpy/birthmove
    copying bnpy/birthmove\BirthProposalError.py -> build\lib.win-amd64-3.6\bnpy/birthmove
    copying bnpy/birthmove\BLogger.py -> build\lib.win-amd64-3.6\bnpy/birthmove
    copying bnpy/birthmove\BPlanner.py -> build\lib.win-amd64-3.6\bnpy/birthmove
    copying bnpy/birthmove\BRestrictedLocalStep.py -> build\lib.win-amd64-3.6\bnpy/birthmove
    copying bnpy/birthmove\TryBirth.py -> build\lib.win-amd64-3.6\bnpy/birthmove
    copying bnpy/birthmove\__init__.py -> build\lib.win-amd64-3.6\bnpy/birthmove
    creating build\lib.win-amd64-3.6\bnpy\callbacks
    copying bnpy/callbacks\CBCalcHeldoutMetricsTopicModel.py -> build\lib.win-amd64-3.6\bnpy/callbacks
    copying bnpy/callbacks\HeldoutMetricsLogger.py -> build\lib.win-amd64-3.6\bnpy/callbacks
    copying bnpy/callbacks\InferHeldoutTopics.py -> build\lib.win-amd64-3.6\bnpy/callbacks
    copying bnpy/callbacks\__init__.py -> build\lib.win-amd64-3.6\bnpy/callbacks
    creating build\lib.win-amd64-3.6\bnpy\config
    copying bnpy/config\__init__.py -> build\lib.win-amd64-3.6\bnpy/config
    creating build\lib.win-amd64-3.6\bnpy\data
    copying bnpy/data\BagOfWordsData.py -> build\lib.win-amd64-3.6\bnpy/data
    copying bnpy/data\DataIterator.py -> build\lib.win-amd64-3.6\bnpy/data
    copying bnpy/data\DataIteratorFromDisk.py -> build\lib.win-amd64-3.6\bnpy/data
    copying bnpy/data\DataObj.py -> build\lib.win-amd64-3.6\bnpy/data
    copying bnpy/data\GraphXData.py -> build\lib.win-amd64-3.6\bnpy/data
    copying bnpy/data\GroupXData.py -> build\lib.win-amd64-3.6\bnpy/data
    copying bnpy/data\SeqOfWordsData.py -> build\lib.win-amd64-3.6\bnpy/data
    copying bnpy/data\XData.py -> build\lib.win-amd64-3.6\bnpy/data
    copying bnpy/data\__init__.py -> build\lib.win-amd64-3.6\bnpy/data
    creating build\lib.win-amd64-3.6\bnpy\deletemove
    copying bnpy/deletemove\DLogger.py -> build\lib.win-amd64-3.6\bnpy/deletemove
    copying bnpy/deletemove\DPlanner.py -> build\lib.win-amd64-3.6\bnpy/deletemove
    copying bnpy/deletemove\TryDelete.py -> build\lib.win-amd64-3.6\bnpy/deletemove
    copying bnpy/deletemove\__init__.py -> build\lib.win-amd64-3.6\bnpy/deletemove
    creating build\lib.win-amd64-3.6\bnpy\init
    copying bnpy/init\FromExistingBregman.py -> build\lib.win-amd64-3.6\bnpy/init
    copying bnpy/init\FromLP.py -> build\lib.win-amd64-3.6\bnpy/init
    copying bnpy/init\FromSaved.py -> build\lib.win-amd64-3.6\bnpy/init
    copying bnpy/init\FromScratchBern.py -> build\lib.win-amd64-3.6\bnpy/init
    copying bnpy/init\FromScratchBregman.py -> build\lib.win-amd64-3.6\bnpy/init
    copying bnpy/init\FromScratchBregmanMixture.py -> build\lib.win-amd64-3.6\bnpy/init
    copying bnpy/init\FromScratchGauss.py -> build\lib.win-amd64-3.6\bnpy/init
    copying bnpy/init\FromScratchMult.py -> build\lib.win-amd64-3.6\bnpy/init
    copying bnpy/init\FromScratchRelational.py -> build\lib.win-amd64-3.6\bnpy/init
    copying bnpy/init\FromTruth.py -> build\lib.win-amd64-3.6\bnpy/init
    copying bnpy/init\__init__.py -> build\lib.win-amd64-3.6\bnpy/init
    creating build\lib.win-amd64-3.6\bnpy\ioutil
    copying bnpy/ioutil\BNPYArgParser.py -> build\lib.win-amd64-3.6\bnpy/ioutil
    copying bnpy/ioutil\CountReader.py -> build\lib.win-amd64-3.6\bnpy/ioutil
    copying bnpy/ioutil\DataReader.py -> build\lib.win-amd64-3.6\bnpy/ioutil
    copying bnpy/ioutil\ModelReader.py -> build\lib.win-amd64-3.6\bnpy/ioutil
    copying bnpy/ioutil\ModelWriter.py -> build\lib.win-amd64-3.6\bnpy/ioutil
    copying bnpy/ioutil\SuffStatBagIO.py -> build\lib.win-amd64-3.6\bnpy/ioutil
    copying bnpy/ioutil\__init__.py -> build\lib.win-amd64-3.6\bnpy/ioutil
    creating build\lib.win-amd64-3.6\bnpy\learnalg
    copying bnpy/learnalg\ElapsedTimeLogger.py -> build\lib.win-amd64-3.6\bnpy/learnalg
    copying bnpy/learnalg\EMAlg.py -> build\lib.win-amd64-3.6\bnpy/learnalg
    copying bnpy/learnalg\LearnAlg.py -> build\lib.win-amd64-3.6\bnpy/learnalg
    copying bnpy/learnalg\MemoVBMovesAlg.py -> build\lib.win-amd64-3.6\bnpy/learnalg
    copying bnpy/learnalg\MOVBAlg.py -> build\lib.win-amd64-3.6\bnpy/learnalg
    copying bnpy/learnalg\SOVBAlg.py -> build\lib.win-amd64-3.6\bnpy/learnalg
    copying bnpy/learnalg\VBAlg.py -> build\lib.win-amd64-3.6\bnpy/learnalg
    copying bnpy/learnalg\__init__.py -> build\lib.win-amd64-3.6\bnpy/learnalg
    creating build\lib.win-amd64-3.6\bnpy\mergemove
    copying bnpy/mergemove\MLogger.py -> build\lib.win-amd64-3.6\bnpy/mergemove
    copying bnpy/mergemove\MPlanner.py -> build\lib.win-amd64-3.6\bnpy/mergemove
    copying bnpy/mergemove\SLogger.py -> build\lib.win-amd64-3.6\bnpy/mergemove
    copying bnpy/mergemove\TryMerge.py -> build\lib.win-amd64-3.6\bnpy/mergemove
    copying bnpy/mergemove\__init__.py -> build\lib.win-amd64-3.6\bnpy/mergemove
    creating build\lib.win-amd64-3.6\bnpy\obsmodel
    copying bnpy/obsmodel\AbstractObsModel.py -> build\lib.win-amd64-3.6\bnpy/obsmodel
    copying bnpy/obsmodel\AutoRegGaussObsModel.py -> build\lib.win-amd64-3.6\bnpy/obsmodel
    copying bnpy/obsmodel\BernObsModel.py -> build\lib.win-amd64-3.6\bnpy/obsmodel
    copying bnpy/obsmodel\DiagGaussObsModel.py -> build\lib.win-amd64-3.6\bnpy/obsmodel
    copying bnpy/obsmodel\GaussObsModel.py -> build\lib.win-amd64-3.6\bnpy/obsmodel
    copying bnpy/obsmodel\GaussRegressYFromDiagGaussXObsModel.py -> build\lib.win-amd64-3.6\bnpy/obsmodel
    copying bnpy/obsmodel\GaussRegressYFromFixedXObsModel.py -> build\lib.win-amd64-3.6\bnpy/obsmodel
    copying bnpy/obsmodel\MultObsModel.py -> build\lib.win-amd64-3.6\bnpy/obsmodel
    copying bnpy/obsmodel\ZeroMeanGaussObsModel.py -> build\lib.win-amd64-3.6\bnpy/obsmodel
    copying bnpy/obsmodel\__init__.py -> build\lib.win-amd64-3.6\bnpy/obsmodel
    creating build\lib.win-amd64-3.6\bnpy\suffstats
    copying bnpy/suffstats\ParamBag.py -> build\lib.win-amd64-3.6\bnpy/suffstats
    copying bnpy/suffstats\SuffStatBag.py -> build\lib.win-amd64-3.6\bnpy/suffstats
    copying bnpy/suffstats\__init__.py -> build\lib.win-amd64-3.6\bnpy/suffstats
    creating build\lib.win-amd64-3.6\bnpy\util
    copying bnpy/util\EntropyUtil.py -> build\lib.win-amd64-3.6\bnpy/util
    copying bnpy/util\MatMultUtil.py -> build\lib.win-amd64-3.6\bnpy/util
    copying bnpy/util\MemoryUtil.py -> build\lib.win-amd64-3.6\bnpy/util
    copying bnpy/util\NumericUtil.py -> build\lib.win-amd64-3.6\bnpy/util
    copying bnpy/util\OptimizerForPi.py -> build\lib.win-amd64-3.6\bnpy/util
    copying bnpy/util\ParallelUtil.py -> build\lib.win-amd64-3.6\bnpy/util
    copying bnpy/util\PrettyPrintUtil.py -> build\lib.win-amd64-3.6\bnpy/util
    copying bnpy/util\RandUtil.py -> build\lib.win-amd64-3.6\bnpy/util
    copying bnpy/util\setup.py -> build\lib.win-amd64-3.6\bnpy/util
    copying bnpy/util\ShapeUtil.py -> build\lib.win-amd64-3.6\bnpy/util
    copying bnpy/util\SparseRespStatsUtil.py -> build\lib.win-amd64-3.6\bnpy/util
    copying bnpy/util\SparseRespUtil.py -> build\lib.win-amd64-3.6\bnpy/util
    copying bnpy/util\SpecialFuncUtil.py -> build\lib.win-amd64-3.6\bnpy/util
    copying bnpy/util\StateSeqUtil.py -> build\lib.win-amd64-3.6\bnpy/util
    copying bnpy/util\StickBreakUtil.py -> build\lib.win-amd64-3.6\bnpy/util
    copying bnpy/util\TextFileReader.py -> build\lib.win-amd64-3.6\bnpy/util
    copying bnpy/util\VerificationUtil.py -> build\lib.win-amd64-3.6\bnpy/util
    copying bnpy/util\__init__.py -> build\lib.win-amd64-3.6\bnpy/util
    creating build\lib.win-amd64-3.6\bnpy\util\lib
    copying bnpy/util\lib\LibLocalStep.py -> build\lib.win-amd64-3.6\bnpy/util\lib
    copying bnpy/util\lib\LibRlogR.py -> build\lib.win-amd64-3.6\bnpy/util\lib
    copying bnpy/util\lib\__init__.py -> build\lib.win-amd64-3.6\bnpy/util\lib
    creating build\lib.win-amd64-3.6\bnpy\util\lib\sparseResp
    copying bnpy/util\lib\sparseResp\CPPLoader.py -> build\lib.win-amd64-3.6\bnpy/util\lib\sparseResp
    copying bnpy/util\lib\sparseResp\LibLocalStepManyDocs.py -> build\lib.win-amd64-3.6\bnpy/util\lib\sparseResp
    copying bnpy/util\lib\sparseResp\LibSparseResp.py -> build\lib.win-amd64-3.6\bnpy/util\lib\sparseResp
    copying bnpy/util\lib\sparseResp\__init__.py -> build\lib.win-amd64-3.6\bnpy/util\lib\sparseResp
    creating build\lib.win-amd64-3.6\bnpy\viz
    copying bnpy/viz\BarsViz.py -> build\lib.win-amd64-3.6\bnpy/viz
    copying bnpy/viz\BernViz.py -> build\lib.win-amd64-3.6\bnpy/viz
    copying bnpy/viz\BestJobSearcher.py -> build\lib.win-amd64-3.6\bnpy/viz
    copying bnpy/viz\GaussViz.py -> build\lib.win-amd64-3.6\bnpy/viz
    copying bnpy/viz\JobFilter.py -> build\lib.win-amd64-3.6\bnpy/viz
    copying bnpy/viz\PlotComps.py -> build\lib.win-amd64-3.6\bnpy/viz
    copying bnpy/viz\PlotCounts.py -> build\lib.win-amd64-3.6\bnpy/viz
    copying bnpy/viz\PlotELBO.py -> build\lib.win-amd64-3.6\bnpy/viz
    copying bnpy/viz\PlotHeldoutLik.py -> build\lib.win-amd64-3.6\bnpy/viz
    copying bnpy/viz\PlotK.py -> build\lib.win-amd64-3.6\bnpy/viz
    copying bnpy/viz\PlotParamComparison.py -> build\lib.win-amd64-3.6\bnpy/viz
    copying bnpy/viz\PlotTrace.py -> build\lib.win-amd64-3.6\bnpy/viz
    copying bnpy/viz\PlotUtil.py -> build\lib.win-amd64-3.6\bnpy/viz
    copying bnpy/viz\PrintTopics.py -> build\lib.win-amd64-3.6\bnpy/viz
    copying bnpy/viz\ProposalViz.py -> build\lib.win-amd64-3.6\bnpy/viz
    copying bnpy/viz\RelationalViz.py -> build\lib.win-amd64-3.6\bnpy/viz
    copying bnpy/viz\SequenceViz.py -> build\lib.win-amd64-3.6\bnpy/viz
    copying bnpy/viz\TaskRanker.py -> build\lib.win-amd64-3.6\bnpy/viz
    copying bnpy/viz\__init__.py -> build\lib.win-amd64-3.6\bnpy/viz
    running egg_info
    writing bnpy.egg-info\PKG-INFO
    writing dependency_links to bnpy.egg-info\dependency_links.txt
    writing requirements to bnpy.egg-info\requires.txt
    writing top-level names to bnpy.egg-info\top_level.txt
    reading manifest file 'bnpy.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'bnpy.egg-info\SOURCES.txt'
    copying bnpy/allocmodel\hmm\lib\FwdBwdRowMajor.cpp -> build\lib.win-amd64-3.6\bnpy/allocmodel\hmm\lib
    copying bnpy/util\EntropyUtilX.pyx -> build\lib.win-amd64-3.6\bnpy/util
    copying bnpy/util\SparseRespUtilX.pyx -> build\lib.win-amd64-3.6\bnpy/util
    copying bnpy/util\TextFileReaderX.pyx -> build\lib.win-amd64-3.6\bnpy/util
    copying bnpy/util\EntropyUtilX.c -> build\lib.win-amd64-3.6\bnpy/util
    copying bnpy/util\SparseRespUtilX.c -> build\lib.win-amd64-3.6\bnpy/util
    copying bnpy/util\TextFileReaderX.c -> build\lib.win-amd64-3.6\bnpy/util
    copying bnpy/util\lib\ForwardBackwardAlg.cpp -> build\lib.win-amd64-3.6\bnpy/util\lib
    copying bnpy/util\lib\LocalStepCore.cpp -> build\lib.win-amd64-3.6\bnpy/util\lib
    copying bnpy/util\lib\RlogRCore.cpp -> build\lib.win-amd64-3.6\bnpy/util\lib
    copying bnpy/util\lib\sparseResp\SparsifyRespCPPX.cpp -> build\lib.win-amd64-3.6\bnpy/util\lib\sparseResp
    copying bnpy/util\lib\sparseResp\TopicModelLocalStepCPPX.cpp -> build\lib.win-amd64-3.6\bnpy/util\lib\sparseResp
    copying bnpy/util\lib\sparseResp\TopicModelLocalStepManyDocsCPPX.cpp -> build\lib.win-amd64-3.6\bnpy/util\lib\sparseResp
    copying bnpy/util\lib\sparseResp\TopLCPPX.cpp -> build\lib.win-amd64-3.6\bnpy/util\lib\sparseResp
    copying bnpy/util\lib\sparseResp\fastexp.h -> build\lib.win-amd64-3.6\bnpy/util\lib\sparseResp
    running build_ext
    skipping 'bnpy/util\SparseRespUtilX.c' Cython extension (up-to-date)
    building 'bnpy.util.SparseRespUtilX' extension
    creating build\temp.win-amd64-3.6
    creating build\temp.win-amd64-3.6\Release
    creating build\temp.win-amd64-3.6\Release\bnpy
    creating build\temp.win-amd64-3.6\Release\bnpy\util
    C:\Users\Twins\Anaconda3\Library\mingw-w64\bin\gcc.exe -mdll -O -Wall -DMS_WIN64 -IC:\Users\Twins\Anaconda3\include -IC:\Users\Twins\Anaconda3\include -c bnpy/util\SparseRespUtilX.c -o build\temp.win-amd64-3.6\Release\bnpy\util\sparseresputilx.o -O3 -ffast-math
    writing build\temp.win-amd64-3.6\Release\bnpy\util\SparseRespUtilX.cp36-win_amd64.def
    C:\Users\Twins\Anaconda3\Library\mingw-w64\bin\gcc.exe -shared -s build\temp.win-amd64-3.6\Release\bnpy\util\sparseresputilx.o build\temp.win-amd64-3.6\Release\bnpy\util\SparseRespUtilX.cp36-win_amd64.def -LC:\Users\Twins\Anaconda3\libs -LC:\Users\Twins\Anaconda3\PCbuild\amd64 -lm -lpython36 -lmsvcr140 -o build\lib.win-amd64-3.6\bnpy\util\SparseRespUtilX.cp36-win_amd64.pyd
    skipping 'bnpy/util\EntropyUtilX.c' Cython extension (up-to-date)
    building 'bnpy.util.EntropyUtilX' extension
    C:\Users\Twins\Anaconda3\Library\mingw-w64\bin\gcc.exe -mdll -O -Wall -DMS_WIN64 -IC:\Users\Twins\Anaconda3\include -IC:\Users\Twins\Anaconda3\include -c bnpy/util\EntropyUtilX.c -o build\temp.win-amd64-3.6\Release\bnpy\util\entropyutilx.o -O3 -ffast-math
    writing build\temp.win-amd64-3.6\Release\bnpy\util\EntropyUtilX.cp36-win_amd64.def
    C:\Users\Twins\Anaconda3\Library\mingw-w64\bin\gcc.exe -shared -s build\temp.win-amd64-3.6\Release\bnpy\util\entropyutilx.o build\temp.win-amd64-3.6\Release\bnpy\util\EntropyUtilX.cp36-win_amd64.def -LC:\Users\Twins\Anaconda3\libs -LC:\Users\Twins\Anaconda3\PCbuild\amd64 -lm -lpython36 -lmsvcr140 -o build\lib.win-amd64-3.6\bnpy\util\EntropyUtilX.cp36-win_amd64.pyd
    skipping 'bnpy/util\TextFileReaderX.c' Cython extension (up-to-date)
    building 'bnpy.util.TextFileReaderX' extension
    C:\Users\Twins\Anaconda3\Library\mingw-w64\bin\gcc.exe -mdll -O -Wall -DMS_WIN64 -IC:\Users\Twins\Anaconda3\include -IC:\Users\Twins\Anaconda3\include -c bnpy/util\TextFileReaderX.c -o build\temp.win-amd64-3.6\Release\bnpy\util\textfilereaderx.o
    bnpy/util\TextFileReaderX.c: In function '__pyx_pf_4bnpy_4util_15TextFileReaderX_read_from_ldac_file':
    bnpy/util\TextFileReaderX.c:2326:20: warning: implicit declaration of function 'getline' [-Wimplicit-function-declaration]
         __pyx_v_read = getline((&__pyx_v_line), (&__pyx_v_l), __pyx_v_cfile);
                        ^
    writing build\temp.win-amd64-3.6\Release\bnpy\util\TextFileReaderX.cp36-win_amd64.def
    C:\Users\Twins\Anaconda3\Library\mingw-w64\bin\gcc.exe -shared -s build\temp.win-amd64-3.6\Release\bnpy\util\textfilereaderx.o build\temp.win-amd64-3.6\Release\bnpy\util\TextFileReaderX.cp36-win_amd64.def -LC:\Users\Twins\Anaconda3\libs -LC:\Users\Twins\Anaconda3\PCbuild\amd64 -lm -lpython36 -lmsvcr140 -o build\lib.win-amd64-3.6\bnpy\util\TextFileReaderX.cp36-win_amd64.pyd
    build\temp.win-amd64-3.6\Release\bnpy\util\textfilereaderx.o:TextFileReaderX.c:(.text+0x12675): undefined reference to `getline'
    collect2.exe: error: ld returned 1 exit status
    error: command 'C:\\Users\\Twins\\Anaconda3\\Library\\mingw-w64\\bin\\gcc.exe' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\Twins\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Twins\\AppData\\Local\\Temp\\pip-req-build-3h70bojb\\setup.py'"'"'; __file__='"'"'C:\\Users\\Twins\\AppData\\Local\\Temp\\pip-req-build-3h70bojb\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Twins\AppData\Local\Temp\pip-record-z2bf6t67\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.
PS C:\WINDOWS\system32\bnpy>

**Comment by cyriltw** [comment]
Hi, bnpy package is very sensitive to the environment and dependencies. I think a reason where your one is failing is 1. its on Python 3 and 2. packages are too new. 

What I'd suggest is try to use this on Python 2 (create a virtual environment) and also use exact version of the packages in this https://bnpy.readthedocs.io/en/latest/installation.html you may have to modify this https://github.com/bnpy/bnpy/blob/master/requirements.txt to say == instead of >=. 

Hope I'm not too late.

**Comment by brainfo** [comment]
Hi,
I found bnpy in conda archiv is not the latest. So I've installed this github version, but it turns out
`import bnpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "bnpy/__init__.py", line 20, in <module>
    import allocmodel
  File "bnpy/allocmodel/__init__.py", line 13, in <module>
    from relational.FiniteSMSB import FiniteSMSB
  File "bnpy/allocmodel/relational/FiniteSMSB.py", line 21, in <module>
    from bnpy.util import StateSeqUtil
  File "bnpy/util/StateSeqUtil.py", line 3, in <module>
    import munkres
  File "/home/data4/jh/anaconda3/envs/py27/lib/python2.7/site-packages/munkres.py", line 79
    def pad_matrix(self, matrix: Matrix, pad_value: int=0) -> Matrix:
                               ^
SyntaxError: invalid syntax`

in pythoon2.7, the correct syntax is matrix=Matrix, right?
since I'm not sure the exact python version, I'm not sure how incompatible it's with version 2.7 and also don't aware of the difficulties ahead.
